### ISSUE TITLE
In-mem: Project Tracker

### ISSUE THREAD

**Issue by pyongjoo** [illinoisdata/sc-project#1]
**Experiments**
- Google spreadsheet (https://docs.google.com/spreadsheets/d/1n4CkAor97ZW2WzVpmYFV-mG2hINyfU3DHCjff4k6S8Y/edit?usp=sharing)
   - [x] Comparing results on jobs
   - [x] Comparing scalability on generated DAGs
- Compare end-to-end refresh time
   - [x] TPC-DS, XX GB, 
      - [x] Determine scale factor
      - [x] Describe how we generate our query workloads based on TPC-DS
   - [x] PostgreSQL
   - [x] Presto
   - [x] Ours
- Study optimization
   - Random: Random+ BFS, Random + DFS
   - Greedy: Greedy + BFS, Greedy + DFS
   - MKP + BFS
   - MKP + Recursive(?) by Chaundra
   - MKP + DFS (ours)
   - ~~MKP + Simulated annealing (also ours; baseline)~~
- Scalability
   - [x] DAG generator
   - [x] MPK

**Experiment setup**
- [x] Data size: 10GB, 25GB, 50GB, 100GB
- [x] Memory size: 2^n MB, n from 0 to 6, not exceeding data size
- [x] Query workload (aka DAG generator)(by Xinyu)

**Implementation**
- [x] Ours
- [x] Setting up Postgres (on our cluster)
- [x] Setting up Presto (on our cluster)

**Paper Writing**
- [x] Overleaf link (https://www.overleaf.com/project/61fb3d0bacada262535ce0ba)
- [x] Method section
- [x] Experiment section
- [x] Related work
- [x] Background
- [x] System overview
- [x] Introduction section
- [x] Abstract

**Comment by pyongjoo** [comment]
![experiments](https://user-images.githubusercontent.com/1316874/161174224-af0e6f91-6674-4494-8803-9af62bed5eb3.jpg)
![intro_bg](https://user-images.githubusercontent.com/1316874/161174238-4978b20e-685c-42e2-9b9c-636333df486d.jpg)

**Comment by pyongjoo** [comment]
TODO (April 4 2022):

- [ ] Billy: Measure the timeline (with rust for save, pyarrow for load)
- [ ] Billy: Update our figures according to the comments below
   - [ ] Timeline chart
- [x] Billy: Edit Related Work
   - [x] Data science: in-memory storage of nodes
   - [x] Algorithms on job scheduling
- [x] Billy: Add system overview section
- [ ] Billy: Add a (conceptual) figure to introduction
- [ ] Yongjoo: Edit/write some sections of paper
   - [ ] Edit introduction (https://github.com/illinoisdata/inmemory_tables/issues/3)
   - [ ] Add background (https://github.com/illinoisdata/inmemory_tables/issues/2)

Comments:
```
% Claim 1: By keeping some data in memory, we can significantly reduce the end-to-end time for updating all the tables. -> Figure 4. 
% Claim 1.5: By showing runtime breakdown, we confirm that the part we save is indeed the data load/store time.
% Claim 1.6: The more memory, the faster the runtime. However, it kinda converges after a while.
% Claim 2: Our optimization algorithm achieves good performance compared to other alternatives.
% Claim 3: Our algorithm is scalable
% Claim 4: Our system is as good as other existing systems

% Claim 1 figure: Current Figure 8: Compare PostgreSQL, Presto+CSV, Presto+Parquet, \system (0GB), \system (32GB)
% Claim 1.5 figure: line chart on the top showing execution breakdown, 2 current charts without color on bottom. There could be some concurrent operations.
% Claim 2 figure: Gray bar (base table + execution), Green bar (save nodes + load nodes). Plot y-bar chart. X-axis are different optimization methods. Y-axis are runtime. 
% Claim 3: Keep current Figure 7 (maybe remove some algorithms)
```

**Comment by pyongjoo** [comment]
![IMG_2625](https://user-images.githubusercontent.com/1316874/161594334-e8f23aa5-7608-4d01-99d7-78f5af783ca5.jpg)

**Comment by pyongjoo** [comment]
TODO (April 8 2022):
- [ ] Billy: Investigate if we can reduce execution time
- [ ] Xinyu: Update architecture figure; Add an intro figure

**Comment by BillyZhaohengLi** [comment]
TODO (April 20 2022):

- [x] Billy: Draw some drafts for the finalized charts
   - [x] MV explanation chart in introduction
   - [x] Gantt chart depicting the idea of memory container
   - [x] Explanation for importance of execution order
   - [x] Explanation of maximal subsets in MKP
   - [x] Gantt chart for actual job in experiments
- [x] Billy: Edit some sections according to updated framework and results
   - [x] System overview
   - [x] Algorithm
   - [x] Experiments
   - [x] Related work

**Comment by BillyZhaohengLi** [comment]
TODO (April 24 2022):

- [ ] Billy/Xinyu: Finalized charts
   - [ ] MV explanation chart in introduction
   - [x] Gantt chart depicting the idea of memory container
   - [x] Explanation for importance of execution order
   - [x] Explanation of maximal subsets in MKP
   - [x] Gantt chart for actual job in experiments
- [ ] Billy: Polish some sections
   - [ ] System overview
   - [x] Problem setup
   - [x] Algorithm
- [ ] Xinyu: Fill in citations 
   - [x] Sketching
   - [ ] topological order refresh
